language: rust
sudo: false
rust:
- 1.17.0
- stable
- beta
- nightly

matrix:
  include:
    - rust: beta
      script: |
        CUPID_FORCE_ENGINE=c cargo run > engine-c
        CUPID_FORCE_ENGINE=std cargo run > engine-std
        diff --unified engine-c engine-std
    - rust: stable
      env:
        - CUPID_PRETEND_CPUID_NOT_AVAILABLE=1
